### ISSUE TITLE
Folder icon when folder is open looks wrong

### ISSUE THREAD

**Issue by yourordinarycat** [nerocui/JitHubFeedback#1]
![image](https://user-images.githubusercontent.com/49221554/125725572-a770cca0-3c7a-4857-821a-ba5d74e265e2.png)

The icon color is applied incorrectly when the folder's open. Dark mode:

![image](https://user-images.githubusercontent.com/49221554/125725793-5adb4870-e2ce-4120-a29c-14b684c9dce3.png)

**Comment by nerocui** [comment]
what OS version are you running? My folder icon looks like this from Windows 10 19043
![image](https://user-images.githubusercontent.com/10738280/125824879-1b9b7cb0-f7e9-4740-bfc9-70eb65c26faf.png)

**Comment by yourordinarycat** [comment]
Tried on Windows 10 and 11, seems like an 11 problem, guess they changed the folder icon?

**Comment by nerocui** [comment]
Yes I think Windows 11 use different icons. I have not tested on Windows 11 yet because JitHub will launch before Windows 11 GA. I'll investigate this once JitHub V1 is stable.

**Comment by nerocui** [comment]
Fixed~
