### ISSUE TITLE
Metro context menu when right clicking text selection

### ISSUE THREAD

**Issue by just1a-person** [nerocui/JitHubFeedback#11]
# Repro steps

- Open a issue in JitHub
- Select some text
- Right click

# Expected Behavior

Fluent context menu

# Actual Behavior 

Metro context menu

# Screenshots

![Metro style context menu](https://user-images.githubusercontent.com/75578443/130015686-6e837127-4af1-441e-a016-29d1ff1a7536.png)

**Comment by nerocui** [comment]
This is because I'm using webview for most of the markdown format text. GitHub uses custom markdown format that the markdown text block in the CommunityToolKit doesn't support. However, this will be resolved post v1. I try to contribute to the CommunityToolKit to make sure GMF is a supported flavor.

**Comment by nerocui** [comment]
Hi @just1a-person , I have just updated JitHub to version 1.5 in the store. This release has a new markdown view that's completely native WinUI. It supports most common GFM syntax and with more to come. I have also open sourced it and JitHub itself [here](https://github.com/nerocui/JitHubV2) if you want to take a look. Keep in mind this does not apply to the code page as that page is not using a custom version of VS Code, so any markdown there will be renderered by the VS Code markdown renderer.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/10738280/229986801-eca7905e-8946-4390-993a-e03e882ba6fa.png">

<img width="888" alt="image" src="https://user-images.githubusercontent.com/10738280/229986739-0ed6c906-9206-4701-a623-fa36aade8884.png">

Please let me know if this solves your feedback.
