### ISSUE TITLE
Search code files using Ctrl + F

### ISSUE THREAD

**Issue by just1a-person** [nerocui/JitHubFeedback#14]
Allow us to search code files using Ctrl + F/Find

**Comment by nerocui** [comment]
Good idea! I'll have a more detailed plan for keyboard shortcuts (maybe for version 1.5) after initial launch

**Comment by nerocui** [comment]
Hi @just1a-person , I just updated JitHub to version 1.5 in the store. In this release it has VS Code integration which has both ctrl + f and ctrl + shift + f for either local or global search. Please give it a go and see if it address your feedback. I'll close this issue for now, but feel free to reopen or create another one if you have further feedback. 

<img width="940" alt="image" src="https://user-images.githubusercontent.com/10738280/229986182-aafa833b-74d0-4519-b8cf-fc2d1fede85b.png">

[Download JitHub From Microsoft Store](https://www.microsoft.com/store/apps/9MXRBJBB552V)
