### ISSUE TITLE
Landing screen in smallest height doesn't show all text

### ISSUE THREAD

**Issue by roxk** [nerocui/JitHubFeedback#17]
**Steps to reproduce**:
1. Launch fresh install app
2. Shrink app to smallest size
3. Observe text is obstructed, and the text is not scrollable

**Screenshot**
![image](https://user-images.githubusercontent.com/16918354/131769321-cd8de34b-f04c-484f-9c7c-3b9e5812576a.png)

**Actually, just smallest height could reproduce it, the card on the right hand side is a standalone UserControl?**
![image](https://user-images.githubusercontent.com/16918354/131769421-5c747f23-5ea8-4feb-95c9-5aa8d1a636fb.png)

This is an otherwise responsive landing page. Good job!

**Comment by nerocui** [comment]
Thanks for reporting! This is definitely something I need to fix. The whole login screen is actually defined in one while, I didn't bother to make separate controls for the card. The right half just takes over once the screen is narrow enough.

**Comment by nerocui** [comment]
This has been fixed by making the text scrollable in smaller screen in version 1.1 released today. Please give it a go!
