### ISSUE TITLE
Use fluent icons

### ISSUE THREAD

**Issue by muznyo** [nerocui/JitHubFeedback#2]
Jithub currently uses segoe mdl2 icons, but also fluent icons in some place. In windows 11 there are fluent icons and it is a new standard.

**Comment by jaigak** [comment]
On Windows 11, using SymbolIcon for everything will automatically result in Fluent Icons instead of MDL2.

**Comment by nerocui** [comment]
We now use fluent icons! Check it out in the new update 1.0.3.0. gonna close this one for now.
