### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by sdifiore** [nerocui/JitHubFeedback#22]
Just a suggestion...

I really miss, when showing the commits, not show de hash code as well.

I have use for it when debugging as reference and would bee very helpful having it!

Thanks

Sergio Di Fiore
+55 14 99721-7702
sergiodifiore@gmail.com

**Comment by nerocui** [comment]
Hi thanks for the suggestion. Do you mind providing a screenshot of where this info would be most helpful to you?

**Comment by sdifiore** [comment]
There it is!

I painted yellow where I thing would be great!

![image](https://user-images.githubusercontent.com/3626453/148443401-e5fc61da-2c64-4c29-99b4-1abc2fb0a23d.png)

**Comment by nerocui** [comment]
Thank you! I'm happening to be improving this area right now. I'll keep this suggestion in mind!

**Comment by nerocui** [comment]
I added this to the new version that I'm about to release in the next few days. In case you didn't know, you could also right click a commit and copy the sha.

**Comment by nerocui** [comment]
This has been addressed in version 1.1 released today. Please give it a go!
