### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by sdifiore** [nerocui/JitHubFeedback#23]
Would be great if when displaying a page containing code it had the line numbers as well.

**Comment by nerocui** [comment]
Agrees, this will be solved in version 1.5

**Comment by nerocui** [comment]
Hi @sdifiore , I just updated JitHub to version 1.5 in the store. This version contains VS Code integration in the code page. Please give it a go to see if that solves this issue. (vs code has line number in the code page, but the commit page that shows code diff still don't) I'll close this for now. Please feel free to reopen or submit another if this doesn't answer your question. 

[Download JitHub From Microsoft Store](https://www.microsoft.com/store/apps/9MXRBJBB552V)
