### ISSUE TITLE
Search text in code display

### ISSUE THREAD

**Issue by sdifiore** [nerocui/JitHubFeedback#25]
When I'm looking to a specific code, I'd like to search for example for all occurrences os "save" something, as example.

As it is now, I have to scroll down the code, paying attention to it, what can be very tedious and, if it happens that the code is too long, chances are that I'll miss some.

Thank you

Sergio Di Fiore
difiores@outlook.com

**Comment by nerocui** [comment]
Thanks for your feedback. I'll put this on backlog

**Comment by nerocui** [comment]
Hi @sdifiore , I think I already tagged you in another issue, but hey good news in JitHub 1.5 (in store right now) I have integrated VS Code into the code view. So you can just use either ctrl + f or ctrl + shift + f to search code either locally or globally. Please let me know if this solves your feedback.

![image](https://user-images.githubusercontent.com/10738280/229987145-4a7fc60f-36bd-4cd3-8335-469833388d4e.png)
