### ISSUE TITLE
Won't show files

### ISSUE THREAD

**Issue by sdifiore** [nerocui/JitHubFeedback#26]
When viewing a specific commit, showing the diff view, traying to switch to the "View Files" do nothing.

Until now happened once, you can viu a picture of it in the link: https://fatecspgov-my.sharepoint.com/:i:/r/personal/sergio_fiore_fatec_sp_gov_br/Documents/Projetos/Glauco/Sistemas/JitHub/ViewFiles.png?csf=1&web=1&e=rHcX6K

If helps, I can add some of you as codeveloper in the project to try by yourselves. Just let me know.

Thanks

Sergio Di Fiore
difiores@outlook.com

**Comment by nerocui** [comment]
Sorry I don;t have access to the link for the screenshot, do you mind uploading it here?
