### ISSUE TITLE
If you click on feedback button, it redirects to issues page, but the indicator is on code navigationview item 

### ISSUE THREAD

**Issue by muznyo** [nerocui/JitHubFeedback#3]
If i click on feedback button, it redirects to issues page, which is intended, but the navigationview indicator isn't on the issues navigationview item, but on code 
![image](https://user-images.githubusercontent.com/24987471/125845350-ccf3702e-8f1a-4eeb-a547-9d13f3039516.png)

**Comment by nerocui** [comment]
This should be fixed in the new update going out today.
