### ISSUE TITLE
Issues page still has outlined ui

### ISSUE THREAD

**Issue by muznyo** [nerocui/JitHubFeedback#4]
in issues list, cards have outlined ui which is inconsistent with other parts of the app 
![image](https://user-images.githubusercontent.com/24987471/125845599-14aabf53-2dd5-4c7e-a56c-6144cf3ef35d.png)

**Comment by nerocui** [comment]
![image](https://user-images.githubusercontent.com/10738280/129762537-aaef3e34-a2b2-4e6e-b911-0d9398239fe4.png)
I guess we can close this now😉
