### ISSUE TITLE
All activities and Repositories headers look off

### ISSUE THREAD

**Issue by muznyo** [nerocui/JitHubFeedback#7]
![image](https://user-images.githubusercontent.com/24987471/125819526-eba4aac3-ebd0-4359-8e85-c67ba2953eeb.png)

It would look better if they had same vertical alignment in my opinion

**Comment by nerocui** [comment]
This should be fixed with the new home page design. Please give it a try

**Comment by muznyo** [comment]
now it's looking fine!
